name: Build GKI S24U Next
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Kernel
        uses: TheWildJames/GKI_KernelSU_SUSFS@main
        with:
          kernel_source: https://android.googlesource.com/kernel/common
          kernel_branch: android15-6.6
          kernel_config: gki_defconfig
          arch: arm64
          clang_version: r522138b
          # Aqui é onde a mágica do nome acontece
          extra_build_commands: CONFIG_LOCALVERSION=-Samsung-S24-Ultra
          
          # Ativando as ferramentas que você quer
          enable_kernelsu: true
          kernelsu_variant: next
          
          enable_susfs: true
          susfs_version: v2.1.0
          
          # Isso ajuda a evitar erros de compilação por avisos bobos
          disable_werror: true
